# Generated by Django 5.0.14 on 2026-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
